### ISSUE TITLE
KLE import broken

### ISSUE THREAD

**Issue by tbaumann** [ergogen/ergogen#94]
When importing a KLE json

```
❯ node src/cli.js ~/Downloads/keyboard-layout.json -o kle
Ergogen v4.0.2 CLI

Interpreting format: KLE (Auto-debug)
Preprocessing input...
Calculating variables...
Parsing points...
Error: Unexpected key "rotate" within field "points.zones.key1.columns.key1col"!
    at exports.assert (/home/tilli/git/ergogen/ergogen/src/assert.js:12:15)
    at exports.unexpected (/home/tilli/git/ergogen/ergogen/src/assert.js:35:9)
    at exports._render_zone (/home/tilli/git/ergogen/ergogen/src/points.js:58:11)
    at exports.parse (/home/tilli/git/ergogen/ergogen/src/points.js:296:26)
    at Object.process (/home/tilli/git/ergogen/ergogen/src/ergogen.js:54:31)
    at /home/tilli/git/ergogen/ergogen/src/cli.js:127:29
    at Object.<anonymous> (/home/tilli/git/ergogen/ergogen/src/cli.js:195:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
```

@mrzealot did some digging and found out that the kle import still uses column level attributes rather than key level ones.

https://github.com/ergogen/ergogen/blob/63684e33d76579548dd0ff88a9db88ca4cec26c2/src/kle.js#L54

The KLE JSON was literally from the ANSI 101 preset in KLE.

**Comment by ceoloide** [comment]
Fixed in v4.2.0
